version: '2'
services:
  rest-service:
    image: djiuc343/restservice:latest
    cpu_shares: 100
    mem_limit: 524288000 
    ports:
     - "80:80"
    links:
     - db
     - redis
    environment:
     - DATABASE_HOST=db
  db:
    image: djiuc343/database:latest
    cpu_shares: 100
    mem_limit: 524288000
    ports:
     - "3306:3306"
  redis:
    image: redis
    ports:
     - "6379:6379"